import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/global.css";
import NavLinks from "./ui/nav-links";
import Footer from "./ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rubinstein Mecanica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} antialiased`}>
        <div className="">
          <div className="">
            <NavLinks />
          </div>
          <div className="">
            {children}
          </div>
          <div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
